# Generated by Django 2.2.13 on 2021-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20210519_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
